"""
CreateDocxTool — convert structured content into a Word (.docx) file.

Zone: GREEN — runs automatically, no human approval required.

Uses python-docx to generate a professional Word document. The file is
saved to the system temp directory. Pass file_path to upload_to_drive.
"""

from __future__ import annotations

import json
import logging
import os
import tempfile
import uuid
from datetime import datetime

from core.tools.base_tool import BaseTool, ToolZone

logger = logging.getLogger(__name__)


class CreateDocxTool(BaseTool):
    """Generate a Word (.docx) file from structured document sections.

    Input format (JSON string)::

        {
            "title":    "Q2 Sales Report",
            "sections": [
                {"heading": "Executive Summary", "content": "..."},
                {"heading": "Key Findings",       "content": "..."}
            ],
            "author":   "KRYPSOS Agent"  (optional)
        }

    Returns::

        {
            "status":    "created",
            "filename":  "Q2_Sales_Report_20260708.docx",
            "file_path": "/tmp/krypsos_docs/Q2_Sales_Report_20260708.docx",
            "size_kb":   18,
            "format":    "docx"
        }
    """

    name: str = "create_docx"
    description: str = (
        "Create a Word (.docx) file from structured document content. "
        "Input JSON: {\"title\": \"...\", \"sections\": [{\"heading\": \"...\", \"content\": \"...\"}], "
        "\"author\": \"...(optional)\"}. "
        "Returns file_path of the created Word document. Pass file_path to upload_to_drive."
    )
    zone: ToolZone = ToolZone.GREEN

    _OUTPUT_DIR = os.path.join(tempfile.gettempdir(), "krypsos_docs")

    def run(self, input_str: str) -> str:
        try:
            data = json.loads(input_str) if isinstance(input_str, str) else input_str
        except (json.JSONDecodeError, TypeError):
            return json.dumps({"error": "Invalid input. Expected JSON with title and sections."})

        title    = data.get("title", "Document")
        sections = data.get("sections", [])
        author   = data.get("author", "KRYPSOS Agent")

        if not sections:
            return json.dumps({"error": "'sections' list is required. Call generate_content first."})

        try:
            return self._build_docx(title, sections, author)
        except ImportError:
            return json.dumps({"error": "python-docx is not installed. Run: pip install python-docx"})
        except Exception as exc:
            logger.exception("CreateDocxTool failed")
            return json.dumps({"error": str(exc)})

    def _build_docx(self, title: str, sections: list, author: str) -> str:
        from docx import Document
        from docx.shared import Pt, RGBColor, Inches
        from docx.enum.text import WD_ALIGN_PARAGRAPH

        os.makedirs(self._OUTPUT_DIR, exist_ok=True)

        safe_title = "".join(c if c.isalnum() or c in " _-" else "_" for c in title)
        date_str   = datetime.now().strftime("%Y%m%d")
        filename   = f"{safe_title.replace(' ', '_')}_{date_str}_{uuid.uuid4().hex[:6]}.docx"
        file_path  = os.path.join(self._OUTPUT_DIR, filename)

        doc = Document()

        # Page margins
        for section in doc.sections:
            section.top_margin    = Inches(1)
            section.bottom_margin = Inches(1)
            section.left_margin   = Inches(1.2)
            section.right_margin  = Inches(1.2)

        # Title
        title_para = doc.add_heading(title, level=0)
        title_para.alignment = WD_ALIGN_PARAGRAPH.LEFT
        run = title_para.runs[0]
        run.font.size  = Pt(22)
        run.font.color.rgb = RGBColor(0x1a, 0x1a, 0x2e)

        # Metadata line
        meta = doc.add_paragraph()
        meta.alignment = WD_ALIGN_PARAGRAPH.LEFT
        meta_run = meta.add_run(
            f"Generated by {author}  |  {datetime.now().strftime('%B %d, %Y')}"
        )
        meta_run.font.size  = Pt(9)
        meta_run.font.color.rgb = RGBColor(0x88, 0x88, 0x88)

        # Horizontal rule (paragraph border workaround)
        doc.add_paragraph("─" * 80)

        # Sections
        for sec in sections:
            heading = sec.get("heading", "")
            content = sec.get("content", "")

            if heading:
                h = doc.add_heading(heading, level=2)
                h.runs[0].font.color.rgb = RGBColor(0x16, 0x21, 0x3e)

            if content:
                for line in content.split("\n"):
                    line = line.strip()
                    if not line:
                        doc.add_paragraph()
                        continue
                    if line.startswith(("- ", "• ", "* ")):
                        p = doc.add_paragraph(style="List Bullet")
                        p.add_run(line[2:]).font.size = Pt(10)
                    else:
                        p = doc.add_paragraph(line)
                        p.runs[0].font.size = Pt(10) if p.runs else None

        doc.save(file_path)

        size_kb = round(os.path.getsize(file_path) / 1024, 1)
        logger.info("CreateDocxTool: created %s (%.1f KB)", filename, size_kb)

        return json.dumps({
            "status":    "created",
            "filename":  filename,
            "file_path": file_path,
            "size_kb":   size_kb,
            "format":    "docx",
        })

    def to_schema(self) -> dict:
        return {"type": "function", "function": {
            "name": self.name, "description": self.description,
            "parameters": {"type": "object",
                "properties": {
                    "title":    {"type": "string"},
                    "sections": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "heading": {"type": "string"},
                                "content": {"type": "string"},
                            },
                        },
                    },
                    "author": {"type": "string"},
                },
                "required": ["title", "sections"],
            },
        }}
