# Generated by Django 4.2.16 on 2026-06-23 06:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('task_created', 'Task Created'), ('task_started', 'Task Started'), ('task_completed', 'Task Completed'), ('task_failed', 'Task Failed'), ('task_cancelled', 'Task Cancelled'), ('tool_called', 'Tool Called'), ('approval_requested', 'Approval Requested'), ('approval_granted', 'Approval Granted'), ('approval_rejected', 'Approval Rejected'), ('auth_login', 'User Login'), ('auth_logout', 'User Logout'), ('integration_connected', 'Integration Connected'), ('integration_revoked', 'Integration Revoked'), ('agent_created', 'Agent Created'), ('agent_updated', 'Agent Updated'), ('agent_deleted', 'Agent Deleted'), ('team_invited', 'Team Member Invited'), ('team_removed', 'Team Member Removed'), ('budget_alert', 'Budget Alert')], max_length=50)),
                ('resource_type', models.CharField(blank=True, max_length=50)),
                ('resource_id', models.CharField(blank=True, max_length=36)),
                ('metadata', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
