# Generated by Django 4.2.16 on 2026-06-23 06:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('agent_type', models.CharField(choices=[('email', 'Email Agent'), ('calendar', 'Calendar Agent'), ('research', 'Research Agent'), ('custom', 'Custom Agent')], default='custom', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('system_prompt', models.TextField(blank=True)),
                ('max_steps', models.PositiveIntegerField(default=20)),
                ('max_cost_usd', models.DecimalField(decimal_places=4, default=1.0, max_digits=8)),
                ('llm_model', models.CharField(default='llama-3.1-8b-instant', max_length=100)),
                ('tools', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agents',
                'ordering': ['-created_at'],
            },
        ),
    ]
