"""
CreatePdfTool — convert structured content into a PDF file.

Zone: GREEN — runs automatically, no human approval required.

Uses reportlab to generate a professional PDF. The file is saved to
the system temp directory and the path + filename are returned.
The upload_to_drive tool then takes the file_path and uploads it.
"""

from __future__ import annotations

import json
import logging
import os
import tempfile
import uuid
from datetime import datetime

from core.tools.base_tool import BaseTool, ToolZone

logger = logging.getLogger(__name__)


class CreatePdfTool(BaseTool):
    """Generate a PDF file from structured document sections.

    Input format (JSON string)::

        {
            "title":    "Q2 Sales Report",
            "sections": [
                {"heading": "Executive Summary", "content": "..."},
                {"heading": "Key Findings",       "content": "..."}
            ],
            "author":   "KRYPSOS Agent"  (optional)
        }

    Returns::

        {
            "status":    "created",
            "filename":  "Q2_Sales_Report_20260708.pdf",
            "file_path": "/tmp/krypsos_docs/Q2_Sales_Report_20260708.pdf",
            "size_kb":   24,
            "pages":     2
        }
    """

    name: str = "create_pdf"
    description: str = (
        "Create a PDF file from structured document content. "
        "Input JSON: {\"title\": \"...\", \"sections\": [{\"heading\": \"...\", \"content\": \"...\"}], "
        "\"author\": \"...(optional)\"}. "
        "Returns file_path of the created PDF. Pass file_path to upload_to_drive to save to Google Drive."
    )
    zone: ToolZone = ToolZone.GREEN

    _OUTPUT_DIR = os.path.join(tempfile.gettempdir(), "krypsos_docs")

    def run(self, input_str: str) -> str:
        try:
            data = json.loads(input_str) if isinstance(input_str, str) else input_str
        except (json.JSONDecodeError, TypeError):
            return json.dumps({"error": "Invalid input. Expected JSON with title and sections."})

        title    = data.get("title", "Document")
        sections = data.get("sections", [])
        author   = data.get("author", "KRYPSOS Agent")

        if not sections:
            return json.dumps({"error": "'sections' list is required. Call generate_content first."})

        try:
            return self._build_pdf(title, sections, author)
        except ImportError:
            return json.dumps({"error": "reportlab is not installed. Run: pip install reportlab"})
        except Exception as exc:
            logger.exception("CreatePdfTool failed")
            return json.dumps({"error": str(exc)})

    def _build_pdf(self, title: str, sections: list, author: str) -> str:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.lib import colors
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, HRFlowable, PageBreak
        )

        os.makedirs(self._OUTPUT_DIR, exist_ok=True)

        safe_title = "".join(c if c.isalnum() or c in " _-" else "_" for c in title)
        date_str   = datetime.now().strftime("%Y%m%d")
        filename   = f"{safe_title.replace(' ', '_')}_{date_str}_{uuid.uuid4().hex[:6]}.pdf"
        file_path  = os.path.join(self._OUTPUT_DIR, filename)

        doc = SimpleDocTemplate(
            file_path,
            pagesize=A4,
            rightMargin=2*cm, leftMargin=2*cm,
            topMargin=2.5*cm, bottomMargin=2*cm,
        )

        styles = getSampleStyleSheet()

        title_style = ParagraphStyle(
            "DocTitle",
            parent=styles["Title"],
            fontSize=22,
            spaceAfter=6,
            textColor=colors.HexColor("#1a1a2e"),
        )
        meta_style = ParagraphStyle(
            "Meta",
            parent=styles["Normal"],
            fontSize=9,
            textColor=colors.grey,
            spaceAfter=12,
        )
        heading_style = ParagraphStyle(
            "SectionHeading",
            parent=styles["Heading2"],
            fontSize=13,
            spaceBefore=14,
            spaceAfter=6,
            textColor=colors.HexColor("#16213e"),
        )
        body_style = ParagraphStyle(
            "Body",
            parent=styles["BodyText"],
            fontSize=10,
            leading=15,
            spaceAfter=8,
        )

        story = []

        # Title + metadata
        story.append(Paragraph(title, title_style))
        meta = f"Generated by {author} &nbsp;|&nbsp; {datetime.now().strftime('%B %d, %Y')}"
        story.append(Paragraph(meta, meta_style))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e0e0e0")))
        story.append(Spacer(1, 0.4*cm))

        # Sections
        for section in sections:
            heading = section.get("heading", "")
            content = section.get("content", "")

            if heading:
                story.append(Paragraph(heading, heading_style))

            if content:
                # Handle bullet points (lines starting with - or •)
                for line in content.split("\n"):
                    line = line.strip()
                    if not line:
                        story.append(Spacer(1, 0.2*cm))
                        continue
                    if line.startswith(("- ", "• ", "* ")):
                        line = "• " + line[2:]
                    story.append(Paragraph(line, body_style))

            story.append(Spacer(1, 0.3*cm))

        doc.build(story)

        size_kb = round(os.path.getsize(file_path) / 1024, 1)
        logger.info("CreatePdfTool: created %s (%.1f KB)", filename, size_kb)

        return json.dumps({
            "status":    "created",
            "filename":  filename,
            "file_path": file_path,
            "size_kb":   size_kb,
            "format":    "pdf",
        })

    def to_schema(self) -> dict:
        return {"type": "function", "function": {
            "name": self.name, "description": self.description,
            "parameters": {"type": "object",
                "properties": {
                    "title":    {"type": "string"},
                    "sections": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "heading": {"type": "string"},
                                "content": {"type": "string"},
                            },
                        },
                    },
                    "author": {"type": "string"},
                },
                "required": ["title", "sections"],
            },
        }}
