# Generated by Django 4.2.16 on 2026-06-23 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('total_tokens', models.PositiveBigIntegerField(default=0)),
                ('task_count', models.PositiveIntegerField(default=0)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_costs', to='authentication.workspace')),
            ],
            options={
                'db_table': 'daily_costs',
                'ordering': ['-date'],
                'unique_together': {('workspace', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='monthly', max_length=10)),
                ('limit_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alert_threshold_pct', models.PositiveSmallIntegerField(default=80)),
                ('alert_status', models.CharField(choices=[('ok', 'OK'), ('warning', 'Warning (>80%)'), ('critical', 'Critical (>95%)')], default='ok', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='authentication.workspace')),
            ],
            options={
                'db_table': 'budgets',
                'unique_together': {('workspace', 'period')},
            },
        ),
    ]
